name: Configure AWS Credentials and Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}  # This is required for temporary credentials
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # Step 1: Terraform Init (change directory to ./dev)
      - name: Terraform Init
        run: terraform init
        working-directory: ./dev  # Set the working directory to where your Terraform files are

      # Step 2: Terraform Validate (change directory to ./dev)
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./dev  # Set the working directory to where your Terraform files are

      # Step 3: Generate Terraform Plan (change directory to ./dev)
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./dev  # Set the working directory to where your Terraform files are

      # Step 4: Apply Terraform Plan (change directory to ./dev)
      - name: Terraform Apply
        if: github.event_name == 'push' # Apply only on push events
        run: terraform apply -auto-approve tfplan
        working-directory: ./dev  # Set the working directory to where your Terraform files are
